WENAP_LOGIN_SUCCESS = 100
WEBAP_LOGIN_FAIL = 101
WEBAP_SERVER_ERROR = 102
WEBAP_ERROR = 103
SEMESTERS_QUERY_ERROR = 104


CACHE_WENAP_LOGIN_SUCCESS = WENAP_LOGIN_SUCCESS+10
CACHE_WEBAP_LOGIN_FAIL = WEBAP_LOGIN_FAIL+10
CACHE_WEBAP_SERVER_ERROR = WEBAP_SERVER_ERROR+10
CACHE_WEBAP_ERROR = WEBAP_ERROR+10

CACHE_AP_QUERY_COOKIE_ERROR = 144
CACHE_AP_QUERY_USERINFO_ERROR = 145

USER_INFO_PARSE_ERROR = 301
USER_INFO_ERROR = 302
MIDTERM_ALERTS_ERROR = 303
SCORES_ERROR = 304
