WENAP_LOGIN_SUCCESS = 100
WEBAP_LOGIN_FAIL = 101
WEBAP_SERVER_ERROR = 102
WEBAP_ERROR = 103

CACHE_WENAP_LOGIN_SUCCESS = WENAP_LOGIN_SUCCESS
CACHE_WEBAP_LOGIN_FAIL = WEBAP_LOGIN_FAIL
CACHE_WEBAP_SERVER_ERROR = WEBAP_SERVER_ERROR
CACHE_WEBAP_ERROR = WEBAP_ERROR
